/*
 * This file is generated by jOOQ.
 */
package com.moseeker.vo.profile.basic;


import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;


/**
 * Profile的求职意向
 */

@Data
@ApiModel(value = "Profile的求职意向")
public class ProfileIntentionVO implements Serializable {

    private static final long serialVersionUID = -1715008600;

    @ApiModelProperty(value = "主键", name = "id", dataType = "Integer")
    private Integer id;
    @ApiModelProperty(value = "简历Id", name = "profileId", dataType = "Integer")
    private Integer profileId;
    @ApiModelProperty(value = "工作类型", dataType = "java.lang.Integer", example = "1")
    private Byte worktype;
    @ApiModelProperty(value = "当前是否在职状态", dataType = "java.lang.Integer", example = "1")
    private Byte workstate;
    @ApiModelProperty(value = "薪资code", dataType = "java.lang.Integer", example = "1")
    private Byte salaryCode;
    @ApiModelProperty(value = "关键词", dataType = "string")
    private String tag;
    @ApiModelProperty(value = "是否考虑创业公司机会", dataType = "java.lang.Integer", example = "1")
    private Byte considerVentureCompanyOpportunities;
    @ApiModelProperty(value = "求职意向-行业")
    private List<ProfileIntentionIndustryVO> industries;
    @ApiModelProperty(value = "求职意向-职能")
    private List<ProfileIntentionPositionVO> positions;
    @ApiModelProperty(value = "求职意向-期望城市")
    private List<ProfileIntentionCityVO> cities;
    @ApiModelProperty(value = "创建时间", dataType = "java.lang.String", example = "2018-11-28 16:00:00")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp createTime;
    @ApiModelProperty(value = "更新时间", dataType = "java.lang.String", example = "2018-11-28 16:00:00")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp updateTime;

}
