/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.profile.basic;


import com.fasterxml.jackson.annotation.JsonFormat;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;


/**
 * 用户profile基础个人信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileBasicVO implements Serializable {

    private static final long serialVersionUID = -1462438542;

    private Integer   profileId;
    private String    name;
    private Byte      gender;
    private Integer   nationalityCode;
    private String    nationalityName;
    private Integer   cityCode;
    private String    cityName;
    private Date      birth;
    private String    weixin;
    private String    qq;
    private String    motto;
    private String    selfIntroduction;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp createTime;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp updateTime;

    public ProfileBasicVO() {}

    public ProfileBasicVO(ProfileBasicVO value) {
        this.profileId = value.profileId;
        this.name = value.name;
        this.gender = value.gender;
        this.nationalityCode = value.nationalityCode;
        this.nationalityName = value.nationalityName;
        this.cityCode = value.cityCode;
        this.cityName = value.cityName;
        this.birth = value.birth;
        this.weixin = value.weixin;
        this.qq = value.qq;
        this.motto = value.motto;
        this.selfIntroduction = value.selfIntroduction;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public ProfileBasicVO(
        Integer   profileId,
        String    name,
        Byte      gender,
        Integer   nationalityCode,
        String    nationalityName,
        Integer   cityCode,
        String    cityName,
        Date      birth,
        String    weixin,
        String    qq,
        String    motto,
        String    selfIntroduction,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.profileId = profileId;
        this.name = name;
        this.gender = gender;
        this.nationalityCode = nationalityCode;
        this.nationalityName = nationalityName;
        this.cityCode = cityCode;
        this.cityName = cityName;
        this.birth = birth;
        this.weixin = weixin;
        this.qq = qq;
        this.motto = motto;
        this.selfIntroduction = selfIntroduction;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getProfileId() {
        return this.profileId;
    }

    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Byte getGender() {
        return this.gender;
    }

    public void setGender(Byte gender) {
        this.gender = gender;
    }

    public Integer getNationalityCode() {
        return this.nationalityCode;
    }

    public void setNationalityCode(Integer nationalityCode) {
        this.nationalityCode = nationalityCode;
    }

    public String getNationalityName() {
        return this.nationalityName;
    }

    public void setNationalityName(String nationalityName) {
        this.nationalityName = nationalityName;
    }

    public Integer getCityCode() {
        return this.cityCode;
    }

    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }

    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public Date getBirth() {
        return this.birth;
    }

    public void setBirth(Date birth) {
        this.birth = birth;
    }

    public String getWeixin() {
        return this.weixin;
    }

    public void setWeixin(String weixin) {
        this.weixin = weixin;
    }

    public String getQq() {
        return this.qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    public String getMotto() {
        return this.motto;
    }

    public void setMotto(String motto) {
        this.motto = motto;
    }

    public String getSelfIntroduction() {
        return this.selfIntroduction;
    }

    public void setSelfIntroduction(String selfIntroduction) {
        this.selfIntroduction = selfIntroduction;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProfileBasicVO (");

        sb.append(profileId);
        sb.append(", ").append(name);
        sb.append(", ").append(gender);
        sb.append(", ").append(nationalityCode);
        sb.append(", ").append(nationalityName);
        sb.append(", ").append(cityCode);
        sb.append(", ").append(cityName);
        sb.append(", ").append(birth);
        sb.append(", ").append(weixin);
        sb.append(", ").append(qq);
        sb.append(", ").append(motto);
        sb.append(", ").append(selfIntroduction);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
