/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.profile.basic;


import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModelProperty;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;


/**
 * Profile的教育经历
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileEducationVO implements Serializable {

    private static final long serialVersionUID = -759170248;

    private Integer   id;
    private Integer   profileId;
    private Date      start;
    private Date      end;
    @ApiModelProperty(value = "endUntilNow", dataType = "java.lang.Integer", example = "1")
    private Byte      endUntilNow;
    private Integer   collegeCode;
    private String    collegeName;
    private String    collegeLogo;
    private String    majorCode;
    private String    majorName;
    @ApiModelProperty(value = "degree", dataType = "java.lang.Integer", example = "1")
    private Byte      degree;
    private String    description;
    @ApiModelProperty(value = "isFull", dataType = "java.lang.Integer", example = "1")
    private Byte      isFull;
    @ApiModelProperty(value = "isUnified", dataType = "java.lang.Integer", example = "1")
    private Byte      isUnified;
    @ApiModelProperty(value = "isStudyAbroad", dataType = "java.lang.Integer", example = "1")
    private Byte      isStudyAbroad;
    private String    studyAbroadCountry;
    @ApiModelProperty(value = "创建时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp createTime;
    @ApiModelProperty(value = "更新时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp updateTime;
    private Integer   countryId;

    public ProfileEducationVO() {}

    public ProfileEducationVO(ProfileEducationVO value) {
        this.id = value.id;
        this.profileId = value.profileId;
        this.start = value.start;
        this.end = value.end;
        this.endUntilNow = value.endUntilNow;
        this.collegeCode = value.collegeCode;
        this.collegeName = value.collegeName;
        this.collegeLogo = value.collegeLogo;
        this.majorCode = value.majorCode;
        this.majorName = value.majorName;
        this.degree = value.degree;
        this.description = value.description;
        this.isFull = value.isFull;
        this.isUnified = value.isUnified;
        this.isStudyAbroad = value.isStudyAbroad;
        this.studyAbroadCountry = value.studyAbroadCountry;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.countryId = value.countryId;
    }

    public ProfileEducationVO(
        Integer   id,
        Integer   profileId,
        Date      start,
        Date      end,
        Byte      endUntilNow,
        Integer   collegeCode,
        String    collegeName,
        String    collegeLogo,
        String    majorCode,
        String    majorName,
        Byte      degree,
        String    description,
        Byte      isFull,
        Byte      isUnified,
        Byte      isStudyAbroad,
        String    studyAbroadCountry,
        Timestamp createTime,
        Timestamp updateTime,
        Integer   countryId
    ) {
        this.id = id;
        this.profileId = profileId;
        this.start = start;
        this.end = end;
        this.endUntilNow = endUntilNow;
        this.collegeCode = collegeCode;
        this.collegeName = collegeName;
        this.collegeLogo = collegeLogo;
        this.majorCode = majorCode;
        this.majorName = majorName;
        this.degree = degree;
        this.description = description;
        this.isFull = isFull;
        this.isUnified = isUnified;
        this.isStudyAbroad = isStudyAbroad;
        this.studyAbroadCountry = studyAbroadCountry;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.countryId = countryId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProfileId() {
        return this.profileId;
    }

    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    public Date getStart() {
        return this.start;
    }

    public void setStart(Date start) {
        this.start = start;
    }

    public Date getEnd() {
        return this.end;
    }

    public void setEnd(Date end) {
        this.end = end;
    }

    public Byte getEndUntilNow() {
        return this.endUntilNow;
    }

    public void setEndUntilNow(Byte endUntilNow) {
        this.endUntilNow = endUntilNow;
    }

    public Integer getCollegeCode() {
        return this.collegeCode;
    }

    public void setCollegeCode(Integer collegeCode) {
        this.collegeCode = collegeCode;
    }

    public String getCollegeName() {
        return this.collegeName;
    }

    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }

    public String getCollegeLogo() {
        return this.collegeLogo;
    }

    public void setCollegeLogo(String collegeLogo) {
        this.collegeLogo = collegeLogo;
    }

    public String getMajorCode() {
        return this.majorCode;
    }

    public void setMajorCode(String majorCode) {
        this.majorCode = majorCode;
    }

    public String getMajorName() {
        return this.majorName;
    }

    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    public Byte getDegree() {
        return this.degree;
    }

    public void setDegree(Byte degree) {
        this.degree = degree;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Byte getIsFull() {
        return this.isFull;
    }

    public void setIsFull(Byte isFull) {
        this.isFull = isFull;
    }

    public Byte getIsUnified() {
        return this.isUnified;
    }

    public void setIsUnified(Byte isUnified) {
        this.isUnified = isUnified;
    }

    public Byte getIsStudyAbroad() {
        return this.isStudyAbroad;
    }

    public void setIsStudyAbroad(Byte isStudyAbroad) {
        this.isStudyAbroad = isStudyAbroad;
    }

    public String getStudyAbroadCountry() {
        return this.studyAbroadCountry;
    }

    public void setStudyAbroadCountry(String studyAbroadCountry) {
        this.studyAbroadCountry = studyAbroadCountry;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getCountryId() {
        return this.countryId;
    }

    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProfileEducation (");

        sb.append(id);
        sb.append(", ").append(profileId);
        sb.append(", ").append(start);
        sb.append(", ").append(end);
        sb.append(", ").append(endUntilNow);
        sb.append(", ").append(collegeCode);
        sb.append(", ").append(collegeName);
        sb.append(", ").append(collegeLogo);
        sb.append(", ").append(majorCode);
        sb.append(", ").append(majorName);
        sb.append(", ").append(degree);
        sb.append(", ").append(description);
        sb.append(", ").append(isFull);
        sb.append(", ").append(isUnified);
        sb.append(", ").append(isStudyAbroad);
        sb.append(", ").append(studyAbroadCountry);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(countryId);

        sb.append(")");
        return sb.toString();
    }
}
