/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.profile.basic;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Profile的求职意向-职能关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileIntentionPositionVO implements Serializable {

    private static final long serialVersionUID = 569002943;

    private Integer id;
    private Integer profileIntentionId;
    private Integer positionCode;
    private String  positionName;

    public ProfileIntentionPositionVO() {}

    public ProfileIntentionPositionVO(ProfileIntentionPositionVO value) {
        this.id = value.id;
        this.profileIntentionId = value.profileIntentionId;
        this.positionCode = value.positionCode;
        this.positionName = value.positionName;
    }

    public ProfileIntentionPositionVO(
        Integer id,
        Integer profileIntentionId,
        Integer positionCode,
        String  positionName
    ) {
        this.id = id;
        this.profileIntentionId = profileIntentionId;
        this.positionCode = positionCode;
        this.positionName = positionName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProfileIntentionId() {
        return this.profileIntentionId;
    }

    public void setProfileIntentionId(Integer profileIntentionId) {
        this.profileIntentionId = profileIntentionId;
    }

    public Integer getPositionCode() {
        return this.positionCode;
    }

    public void setPositionCode(Integer positionCode) {
        this.positionCode = positionCode;
    }

    public String getPositionName() {
        return this.positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProfileIntentionPositionVO (");

        sb.append(id);
        sb.append(", ").append(profileIntentionId);
        sb.append(", ").append(positionCode);
        sb.append(", ").append(positionName);

        sb.append(")");
        return sb.toString();
    }
}
