/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.profile.basic;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Profile的求职意向-期望城市关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileIntentionCityVO implements Serializable {

    private static final long serialVersionUID = -702243494;

    private Integer id;
    private Integer profileIntentionId;
    private Integer cityCode;
    private String  cityName;

    public ProfileIntentionCityVO() {}

    public ProfileIntentionCityVO(ProfileIntentionCityVO value) {
        this.id = value.id;
        this.profileIntentionId = value.profileIntentionId;
        this.cityCode = value.cityCode;
        this.cityName = value.cityName;
    }

    public ProfileIntentionCityVO(
        Integer id,
        Integer profileIntentionId,
        Integer cityCode,
        String  cityName
    ) {
        this.id = id;
        this.profileIntentionId = profileIntentionId;
        this.cityCode = cityCode;
        this.cityName = cityName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProfileIntentionId() {
        return this.profileIntentionId;
    }

    public void setProfileIntentionId(Integer profileIntentionId) {
        this.profileIntentionId = profileIntentionId;
    }

    public Integer getCityCode() {
        return this.cityCode;
    }

    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }

    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProfileIntentionCityVO (");

        sb.append(id);
        sb.append(", ").append(profileIntentionId);
        sb.append(", ").append(cityCode);
        sb.append(", ").append(cityName);

        sb.append(")");
        return sb.toString();
    }
}
