/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.profile.basic;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * Profile的个人作品
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileWorksVO implements Serializable {

    private static final long serialVersionUID = 737558154;

    private Integer   id;
    private Integer   profileId;
    private String    name;
    private String    url;
    private String    cover;
    private String    description;
    private Timestamp createTime;
    private Timestamp updateTime;

    public ProfileWorksVO() {}

    public ProfileWorksVO(ProfileWorksVO value) {
        this.id = value.id;
        this.profileId = value.profileId;
        this.name = value.name;
        this.url = value.url;
        this.cover = value.cover;
        this.description = value.description;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public ProfileWorksVO(
        Integer   id,
        Integer   profileId,
        String    name,
        String    url,
        String    cover,
        String    description,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.profileId = profileId;
        this.name = name;
        this.url = url;
        this.cover = cover;
        this.description = description;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProfileId() {
        return this.profileId;
    }

    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getCover() {
        return this.cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProfileWorksVO (");

        sb.append(id);
        sb.append(", ").append(profileId);
        sb.append(", ").append(name);
        sb.append(", ").append(url);
        sb.append(", ").append(cover);
        sb.append(", ").append(description);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
