/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.dict.basic;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * 行业一级分类字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictIndustryTypeVO implements Serializable {

    private static final long serialVersionUID = -1831559068;

    public Integer code;
    public String  name;
    public String  companyImg;
    public String  jobImg;
    public String  teamImg;
    public String  pcImg;

    public DictIndustryTypeVO() {}

    public DictIndustryTypeVO(DictIndustryTypeVO value) {
        this.code = value.code;
        this.name = value.name;
        this.companyImg = value.companyImg;
        this.jobImg = value.jobImg;
        this.teamImg = value.teamImg;
        this.pcImg = value.pcImg;
    }

    public DictIndustryTypeVO(
        Integer code,
        String  name,
        String  companyImg,
        String  jobImg,
        String  teamImg,
        String  pcImg
    ) {
        this.code = code;
        this.name = name;
        this.companyImg = companyImg;
        this.jobImg = jobImg;
        this.teamImg = teamImg;
        this.pcImg = pcImg;
    }

    public Integer getCode() {
        return this.code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCompanyImg() {
        return this.companyImg;
    }

    public void setCompanyImg(String companyImg) {
        this.companyImg = companyImg;
    }

    public String getJobImg() {
        return this.jobImg;
    }

    public void setJobImg(String jobImg) {
        this.jobImg = jobImg;
    }

    public String getTeamImg() {
        return this.teamImg;
    }

    public void setTeamImg(String teamImg) {
        this.teamImg = teamImg;
    }

    public String getPcImg() {
        return this.pcImg;
    }

    public void setPcImg(String pcImg) {
        this.pcImg = pcImg;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DictIndustryTypeVO (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(companyImg);
        sb.append(", ").append(jobImg);
        sb.append(", ").append(teamImg);
        sb.append(", ").append(pcImg);

        sb.append(")");
        return sb.toString();
    }
}
