/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.dict.basic;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * 职能分类字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictPositionVO implements Serializable {

    private static final long serialVersionUID = 264367984;

    public Integer code;
    public String  name;
    public Integer parent;
    public Byte    level;

    public DictPositionVO() {}

    public DictPositionVO(DictPositionVO value) {
        this.code = value.code;
        this.name = value.name;
        this.parent = value.parent;
        this.level = value.level;
    }

    public DictPositionVO(
        Integer code,
        String  name,
        Integer parent,
        Byte    level
    ) {
        this.code = code;
        this.name = name;
        this.parent = parent;
        this.level = level;
    }

    public Integer getCode() {
        return this.code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getParent() {
        return this.parent;
    }

    public void setParent(Integer parent) {
        this.parent = parent;
    }

    public Byte getLevel() {
        return this.level;
    }

    public void setLevel(Byte level) {
        this.level = level;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DictPositionVO (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(parent);
        sb.append(", ").append(level);

        sb.append(")");
        return sb.toString();
    }
}
