/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.dict.basic;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * 城市字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictCountryPO implements Serializable {

    private static final long serialVersionUID = 2112427357;

    public Integer id;
    public String  name;
    public String  ename;
    public String  isoCode_2;
    public String  isoCode_3;
    public String  code;
    public Byte    smsEnabled;
    public String  iconClass;
    public Byte    hotCountry;
    public Integer continentCode;
    public Short   priority;

    public DictCountryPO() {}

    public DictCountryPO(DictCountryPO value) {
        this.id = value.id;
        this.name = value.name;
        this.ename = value.ename;
        this.isoCode_2 = value.isoCode_2;
        this.isoCode_3 = value.isoCode_3;
        this.code = value.code;
        this.smsEnabled = value.smsEnabled;
        this.iconClass = value.iconClass;
        this.hotCountry = value.hotCountry;
        this.continentCode = value.continentCode;
        this.priority = value.priority;
    }

    public DictCountryPO(
        Integer id,
        String  name,
        String  ename,
        String  isoCode_2,
        String  isoCode_3,
        String  code,
        Byte    smsEnabled,
        String  iconClass,
        Byte    hotCountry,
        Integer continentCode,
        Short   priority
    ) {
        this.id = id;
        this.name = name;
        this.ename = ename;
        this.isoCode_2 = isoCode_2;
        this.isoCode_3 = isoCode_3;
        this.code = code;
        this.smsEnabled = smsEnabled;
        this.iconClass = iconClass;
        this.hotCountry = hotCountry;
        this.continentCode = continentCode;
        this.priority = priority;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEname() {
        return this.ename;
    }

    public void setEname(String ename) {
        this.ename = ename;
    }

    public String getIsoCode_2() {
        return this.isoCode_2;
    }

    public void setIsoCode_2(String isoCode_2) {
        this.isoCode_2 = isoCode_2;
    }

    public String getIsoCode_3() {
        return this.isoCode_3;
    }

    public void setIsoCode_3(String isoCode_3) {
        this.isoCode_3 = isoCode_3;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Byte getSmsEnabled() {
        return this.smsEnabled;
    }

    public void setSmsEnabled(Byte smsEnabled) {
        this.smsEnabled = smsEnabled;
    }

    public String getIconClass() {
        return this.iconClass;
    }

    public void setIconClass(String iconClass) {
        this.iconClass = iconClass;
    }

    public Byte getHotCountry() {
        return this.hotCountry;
    }

    public void setHotCountry(Byte hotCountry) {
        this.hotCountry = hotCountry;
    }

    public Integer getContinentCode() {
        return this.continentCode;
    }

    public void setContinentCode(Integer continentCode) {
        this.continentCode = continentCode;
    }

    public Short getPriority() {
        return this.priority;
    }

    public void setPriority(Short priority) {
        this.priority = priority;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DictCountryVO (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(ename);
        sb.append(", ").append(isoCode_2);
        sb.append(", ").append(isoCode_3);
        sb.append(", ").append(code);
        sb.append(", ").append(smsEnabled);
        sb.append(", ").append(iconClass);
        sb.append(", ").append(hotCountry);
        sb.append(", ").append(continentCode);
        sb.append(", ").append(priority);

        sb.append(")");
        return sb.toString();
    }
}
