/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.dict.basic;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * 学校字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictCollegeVO implements Serializable {

    private static final long serialVersionUID = 436776184;

    public Integer code;
    public String  name;
    public Integer province;
    public String  logo;

    public DictCollegeVO() {}

    public DictCollegeVO(DictCollegeVO value) {
        this.code = value.code;
        this.name = value.name;
        this.province = value.province;
        this.logo = value.logo;
    }

    public DictCollegeVO(
        Integer code,
        String  name,
        Integer province,
        String  logo
    ) {
        this.code = code;
        this.name = name;
        this.province = province;
        this.logo = logo;
    }

    public Integer getCode() {
        return this.code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getProvince() {
        return this.province;
    }

    public void setProvince(Integer province) {
        this.province = province;
    }

    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DictCollegeVO (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(province);
        sb.append(", ").append(logo);

        sb.append(")");
        return sb.toString();
    }
}
