/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.dict.basic;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * 专业字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictMajorPO implements Serializable {

    private static final long serialVersionUID = -1006484431;

    public String code;
    public String name;
    public Byte   level;

    public DictMajorPO() {}

    public DictMajorPO(DictMajorPO value) {
        this.code = value.code;
        this.name = value.name;
        this.level = value.level;
    }

    public DictMajorPO(
        String code,
        String name,
        Byte   level
    ) {
        this.code = code;
        this.name = name;
        this.level = level;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Byte getLevel() {
        return this.level;
    }

    public void setLevel(Byte level) {
        this.level = level;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DictMajorVO (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(level);

        sb.append(")");
        return sb.toString();
    }
}
