/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.dict.basic;


import io.swagger.annotations.ApiModel;
import lombok.Data;

import java.io.Serializable;


/**
 * 功能描述:
 *
 * @auther: JackYang
 * @return: 
 * @date: 2018/11/15 14:14
 */
@ApiModel(value = "职能分类字典表")
@Data
public class DictPositionVO implements Serializable {

    private static final long serialVersionUID = 4918810549551173937L;
    private Integer code;
    private String  name;
    private Integer parent;
    private Byte    level;


}
