/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.dict.basic;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * 公司所属行业字典
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictIndustryPO implements Serializable {

    private static final long serialVersionUID = 333527074;

    public Integer code;
    public String  name;
    public Integer type;

    public DictIndustryPO() {}

    public DictIndustryPO(DictIndustryPO value) {
        this.code = value.code;
        this.name = value.name;
        this.type = value.type;
    }

    public DictIndustryPO(
        Integer code,
        String  name,
        Integer type
    ) {
        this.code = code;
        this.name = name;
        this.type = type;
    }

    public Integer getCode() {
        return this.code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Industry (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
