/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.dict.basic;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * 城市字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictCityPO implements Serializable {

    private static final long serialVersionUID = -1993585188;

    public Integer code;
    public String  name;
    public Byte    level;
    public Byte    hotCity;
    public String  ename;
    public Byte    isUsing;

    public DictCityPO() {}

    public DictCityPO(DictCityPO value) {
        this.code = value.code;
        this.name = value.name;
        this.level = value.level;
        this.hotCity = value.hotCity;
        this.ename = value.ename;
        this.isUsing = value.isUsing;
    }

    public DictCityPO(
        Integer code,
        String  name,
        Byte    level,
        Byte    hotCity,
        String  ename,
        Byte    isUsing
    ) {
        this.code = code;
        this.name = name;
        this.level = level;
        this.hotCity = hotCity;
        this.ename = ename;
        this.isUsing = isUsing;
    }

    public Integer getCode() {
        return this.code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Byte getLevel() {
        return this.level;
    }

    public void setLevel(Byte level) {
        this.level = level;
    }

    public Byte getHotCity() {
        return this.hotCity;
    }

    public void setHotCity(Byte hotCity) {
        this.hotCity = hotCity;
    }

    public String getEname() {
        return this.ename;
    }

    public void setEname(String ename) {
        this.ename = ename;
    }

    public Byte getIsUsing() {
        return this.isUsing;
    }

    public void setIsUsing(Byte isUsing) {
        this.isUsing = isUsing;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("City (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(level);
        sb.append(", ").append(hotCity);
        sb.append(", ").append(ename);
        sb.append(", ").append(isUsing);

        sb.append(")");
        return sb.toString();
    }
}
