/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.dict.basic;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictConstantPO implements Serializable {

    private static final long serialVersionUID = -1834433401;

    public Integer   id;
    public Integer   code;
    public String    name;
    public Byte      priority;
    public Integer   parentCode;
    public Timestamp createTime;
    public Timestamp updateTime;

    public DictConstantPO() {}

    public DictConstantPO(DictConstantPO value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.priority = value.priority;
        this.parentCode = value.parentCode;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public DictConstantPO(
        Integer   id,
        Integer   code,
        String    name,
        Byte      priority,
        Integer   parentCode,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.priority = priority;
        this.parentCode = parentCode;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCode() {
        return this.code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Byte getPriority() {
        return this.priority;
    }

    public void setPriority(Byte priority) {
        this.priority = priority;
    }

    public Integer getParentCode() {
        return this.parentCode;
    }

    public void setParentCode(Integer parentCode) {
        this.parentCode = parentCode;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DictConstantVO (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(priority);
        sb.append(", ").append(parentCode);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
