/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.sql.Timestamp;


/**
 * 企业邮件总量信息表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "企业邮件总量信息")
public class HrCompanyEmailInfoVO {

    private Integer   id;
    private Integer   companyId;
    @ApiModelProperty(value = "邮件总量")
    private Integer   total;
    @ApiModelProperty(value = "邮件剩余量")
    private Integer   balance;
    @ApiModelProperty(value = "创建时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp createTime;
    @ApiModelProperty(value = "更新时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp updateTime;

}
