/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.sql.Timestamp;


/**
 * 人才库标签表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "人才库标签表")
public class TalentpoolTagVO {

    private Integer   id;
    @ApiModelProperty(value = "hr标签名称")
    private String    name;
    @ApiModelProperty(value = "hr标签ID")
    private Integer   hrId;
    @ApiModelProperty(value = "人才数量")
    private Integer   talentNum;
    @ApiModelProperty(value = "创建时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp createTime;
    @ApiModelProperty(value = "更新时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp updateTime;

}
