/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.sql.Timestamp;


/**
 * 人才库人HR与标签的关系
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "人才库人HR与标签的关系")
public class TalentpoolCommentVO {
    private Integer   id;
    @ApiModelProperty(value = "备注内容",example = "备注内容")
    private String    content;
    @ApiModelProperty(value = "HR ID",example = "82752")
    private Integer   hrId;
    @ApiModelProperty(value = "user ID",example = "5278374")
    private Integer   userId;
    @ApiModelProperty(value = "创建时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp createTime;
    @ApiModelProperty(value = "更新时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp updateTime;
    @ApiModelProperty(value = "公司 ID",example = "39978" )
    private Integer   companyId;

}
