/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.sql.Date;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "简历搬家")
public class TalentpoolProfileMoveVO {


    private Integer   id;
    private Integer   hrId;
    @ApiModelProperty(value = "渠道  1 、51job  3、智联", dataType="java.lang.Integer")
    private Byte      channel;
    private Date      startDate;
    private Date      endDate;
    @ApiModelProperty(value = "创建时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp createTime;
    @ApiModelProperty(value = "更新时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp updateTime;

}
