/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.sql.Date;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "简历搬家")
public class TalentpoolProfileMoveVO {


    private Integer   id;
    private Integer   hrId;
    @ApiModelProperty(value = "渠道  1 、51job  3、智联", dataType="java.lang.Integer")
    private Byte      channel;
    private Date      startDate;
    private Date      endDate;
    private Timestamp createTime;
    private Timestamp updateTime;

}
