/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.sql.Timestamp;


/**
 * 人才库人才表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "人才库人才")
public class TalentpoolTalentVO {

    private Integer   userId;
    private Integer   companyId;
    @ApiModelProperty(value = "收藏次数")
    private Integer   collectNum;
    @ApiModelProperty(value = "公开次数")
    private Integer   publicNum;
    @ApiModelProperty(value = "0 非上传，1上传", dataType="java.lang.Integer")
    private Byte      upload;
    private Timestamp createTime;
    private Timestamp updateTime;

}
