/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 简历筛选项执行表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "简历筛选项执行")
public class TalentpoolProfileFilterExecuteVO {

    @ApiModelProperty(value = "筛选项id")
    private Integer filterId;
    @ApiModelProperty(value = "执行行为")
    private Integer executeId;

}