/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.sql.Timestamp;


/**
 * 人才库简历上传记录表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "人才库简历上传记录")
public class TalentpoolUploadVO {

    private Integer   id;
    @ApiModelProperty(value = "文件名称")
    private String    fileName;
    private Integer   hrId;
    private Integer   companyId;
    private Timestamp createTime;
    private Timestamp updateTime;

}
