/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.sql.Timestamp;


/**
 * 人才库邮件模板表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "人才库邮件模板表")
public class TalentpoolEmailVO {
    private Integer   id;
    @ApiModelProperty(value = "状态 0是不开启 1是开启 2 关闭")
    private Integer   disable;
    @ApiModelProperty(value = "邮件自定义落款")
    private String    inscribe;
    @ApiModelProperty(value = "邮件自定义文案")
    private String    context;
    @ApiModelProperty(value = "邮件配置模板id")
    private Integer   configId;
    @ApiModelProperty(value = "创建时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp createTime;
    @ApiModelProperty(value = "更新时间", dataType= "string", example = "2018-12-10 10:12:45")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp updateTime;
    private Integer   companyId;

}
