/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import io.swagger.annotations.ApiModel;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 企业标签和人才关系表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "企业标签和人才关系")
public class TalentpoolCompanyTagUserVO {

    private Integer tagId;
    private Integer userId;


}
