/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.sql.Timestamp;


/**
 * 人才库人收藏记录
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "人才库人收藏记录")
public class TalentpoolHrTalentVO {

    private Integer   hrId;
    private Integer   userId;
    @ApiModelProperty(value = "1 公开，0 不公开", dataType="java.lang.Integer")
    private Byte      public_;
    private Timestamp createTime;
    private Timestamp updateTime;


}
