/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.sql.Timestamp;


/**
 * 凡是记录在该表的手机号对应的简历都是已成功入库的简历搬家简历，
 * 但是如果简历搬家失败时根据status字段标记出哪些简历是搬家失败的，下次搬家时不会因为重新合并一次导致数据不准确
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "简历搬家")
public class TalentpoolProfileMoveDetailVO {

    private Integer   id;
    private Long      mobile;
    @ApiModelProperty(value = "talentpool_profile_move_record.id，对应的是上一次搬家的操作id")
    private Integer   profileMoveId;
    @ApiModelProperty(value = "该手机号对应的简历搬家成功状态 0 失败 1 成功", dataType="java.lang.Integer")
    private Byte      profileMoveStatus;
    private Timestamp createTime;
    private Timestamp updateTime;

}
