/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.messaging;


import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 通知消息模板表
 */
@Data
public class ATSProcessNoticeTemplateVO{

    @ApiModelProperty(name="id",value = "id",required = false)
    private Integer   id;
    @ApiModelProperty(name="companyId",value = "公司编号",required = false)
    private Integer   companyId;
    @ApiModelProperty(name="name",value = "模板名称",required = false)
    private String    name;
    @ApiModelProperty(name="type",value = "模板类型",required = false)
    private Integer   type;
    @ApiModelProperty(name="status",value = "状态，0：删除，1：开启",required = false)
    private Integer   status;
    @ApiModelProperty(name="createTime",value = "创建时间",required = false)
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp createTime;
    @ApiModelProperty(name="updateTime",value = "更新时间",required = false)
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp updateTime;
}
