/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.dict.response;


import io.swagger.annotations.ApiModel;
import lombok.Data;

import java.io.Serializable;


@ApiModel(value = "学校字典表")
@Data
public class DictCollegeVO implements Serializable {


    private static final long serialVersionUID = -5091487502336372827L;

    private Integer code;
    private String  name;
    private Integer province;
    private String  logo;
    private Integer countryCode;


}
