/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company;


import com.moseeker.vo.company.basic.HrWxNewsReplyVO;
import com.moseeker.vo.company.basic.HrWxRuleVO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 微信回复规则表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "微信回复规则")
public class HrWxRuleReqVO {

    @ApiModelProperty(value = "微信回复规则")
    private HrWxRuleVO rule;
    @ApiModelProperty(value = "文本回复信息（专用）")
    private String  content;
    @ApiModelProperty(value = "图片回复信息（专用）")
    private String  image;
    @ApiModelProperty(value = "图文回复信息（专用）")
    private List<HrWxNewsReplyVO> newsReplys;

}
