/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basc;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;



@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "hr申请人才库记录表")
public class TalentpoolApplicationVO {

    private Integer   hrId;
    private Integer   companyId;
    private Timestamp createTime;
    private Timestamp updateTime;
    @ApiModelProperty(value = "0开启普通人才库，1开启高端人才库")
    private Integer   type;

}
