/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basc;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 人才库人HR与标签的关系
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "人才库人HR与标签的关系")
public class TalentpoolCommentVO {

    private Integer   id;
    @ApiModelProperty(value = "备注内容")
    private String    content;
    private Integer   hrId;
    private Integer   userId;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Integer   companyId;

}
