/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basc;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 人才标签表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "人才标签")
public class TalentpoolUserTagVO {

    private Integer   userId;
    @ApiModelProperty(value = "标签编号")
    private Integer   tagId;
    private Timestamp createTime;
    private Timestamp updateTime;

}
