/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.talentpool.basc;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 人才库邮件模板表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "人才库邮件模板表")
public class TalentpoolEmailVO {
    private Integer   id;
    @ApiModelProperty(value = "状态 0是不开启 1是开启 2 关闭")
    private Integer   disable;
    @ApiModelProperty(value = "邮件自定义落款")
    private String    inscribe;
    @ApiModelProperty(value = "邮件自定义文案")
    private String    context;
    @ApiModelProperty(value = "邮件配置模板id")
    private Integer   configId;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Integer   companyId;

}
