/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode
public class CampaignPcBannerVO {

    private Integer   id;
    private String    href;
    private String    imgUrl;
    private Byte      disable;
    private Timestamp createTime;
    private Timestamp updateTime;


}
