/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 部门主题表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "部门主题")
public class ConfigSysThemeVO{

    private static final long serialVersionUID = 160105368;

    private Integer   id;
    @ApiModelProperty(value = "背景色")
    private String    backgroundColor;
    @ApiModelProperty(value = "标题颜色")
    private String    titleColor;
    @ApiModelProperty(value = "按钮颜色")
    private String    buttonColor;
    @ApiModelProperty(value = "other")
    private String    otherColor;
    @ApiModelProperty(value = "是否免费 0：免费 1：收费，只能在大岂后台操作收费主题")
    private Byte      free;
    @ApiModelProperty(value = "排序优先级")
    private Short     prority;
    @ApiModelProperty(value = "是否禁用 0：可用1：不可用")
    private Byte      disable;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Integer   companyId;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getBackgroundColor() {
        return backgroundColor;
    }

    public void setBackgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor;
    }

    public String getTitleColor() {
        return titleColor;
    }

    public void setTitleColor(String titleColor) {
        this.titleColor = titleColor;
    }

    public String getButtonColor() {
        return buttonColor;
    }

    public void setButtonColor(String buttonColor) {
        this.buttonColor = buttonColor;
    }

    public String getOtherColor() {
        return otherColor;
    }

    public void setOtherColor(String otherColor) {
        this.otherColor = otherColor;
    }

    public Byte getFree() {
        return free;
    }

    public void setFree(Byte free) {
        this.free = free;
    }

    public Short getPrority() {
        return prority;
    }

    public void setPrority(Short prority) {
        this.prority = prority;
    }

    public Byte getDisable() {
        return disable;
    }

    public void setDisable(Byte disable) {
        this.disable = disable;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}
