/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 部门主题表
 */
@Data
@EqualsAndHashCode
public class ConfigSysThemeVO{

    private static final long serialVersionUID = 160105368;

    private Integer   id;
    private String    backgroundColor;
    private String    titleColor;
    private String    buttonColor;
    private String    otherColor;
    private Byte      free;
    private Short     prority;
    private Byte      disable;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Integer   companyId;

}
