/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 公司表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "公司信息")
public class HrCompanyVO {

    private Integer   id;
    @ApiModelProperty(value = " 企业用户:0 ,免费用户:1 , 其它:2")
    private Byte      type;
    @ApiModelProperty(value = "公司注册名称")
    private String    name;
    @ApiModelProperty(value = "公司介绍")
    private String    introduction;
    @ApiModelProperty(value = "公司规模")
    private Byte      scale;
    @ApiModelProperty(value = "公司地址")
    private String    address;
    @ApiModelProperty(value = "公司性质 0:未填写 1:外商独资 3:国企 4:合资 5:民营公司 6:事业单位 7:上市公司 8:政府机关/非盈利机构 10:代表处 11:股份制企业 12:创业公司 13:其它")
    private Byte      property;
    @ApiModelProperty(value = "所属行业")
    private String    industry;
    @ApiModelProperty(value = "公司主页")
    private String    homepage;
    @ApiModelProperty(value = "公司logo的网络cdn地址")
    private String    logo;
    @ApiModelProperty(value = "公司简称")
    private String    abbreviation;
    @ApiModelProperty(value = "json格式的企业印象")
    private String    impression;
    @ApiModelProperty(value = "json格式的企业banner")
    private String    banner;
    @ApiModelProperty(value = "上级公司")
    private Integer   parentId;
    @ApiModelProperty(value = "公司联系人, hr_account.id")
    private Integer   hraccountId;
    @ApiModelProperty(value = "0:无效 1:有效, 删除子公司使用， 母公司目前没有禁用功能")
    private Byte      disable;
    private Timestamp createTime;
    private Timestamp updateTime;
    @ApiModelProperty(value = "添加来源 0:hr系统, 1:官网下载行业报告, 6:无线官网添加, 7:PC端 添加, 8:微信端添加, 9:PC导入, 10:微信端导入, 11 : 程序导入（和黄导入）")
    private Byte      source;
    @ApiModelProperty(value = "公司口号")
    private String    slogan;
    @ApiModelProperty(value = "是否世界500强，0：不是 1：是")
    private Byte      fortune;
    @ApiModelProperty(value = "公司福利特色， 由公司下的职位的福利特色每天跑脚本合并而来，目前供支付宝使用")
    private String    feature;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public Byte getScale() {
        return scale;
    }

    public void setScale(Byte scale) {
        this.scale = scale;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Byte getProperty() {
        return property;
    }

    public void setProperty(Byte property) {
        this.property = property;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public String getHomepage() {
        return homepage;
    }

    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    public String getImpression() {
        return impression;
    }

    public void setImpression(String impression) {
        this.impression = impression;
    }

    public String getBanner() {
        return banner;
    }

    public void setBanner(String banner) {
        this.banner = banner;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public Integer getHraccountId() {
        return hraccountId;
    }

    public void setHraccountId(Integer hraccountId) {
        this.hraccountId = hraccountId;
    }

    public Byte getDisable() {
        return disable;
    }

    public void setDisable(Byte disable) {
        this.disable = disable;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Byte getSource() {
        return source;
    }

    public void setSource(Byte source) {
        this.source = source;
    }

    public String getSlogan() {
        return slogan;
    }

    public void setSlogan(String slogan) {
        this.slogan = slogan;
    }

    public Byte getFortune() {
        return fortune;
    }

    public void setFortune(Byte fortune) {
        this.fortune = fortune;
    }

    public String getFeature() {
        return feature;
    }

    public void setFeature(String feature) {
        this.feature = feature;
    }
}
