/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 公司级别的配置信息表
 */
@Data
@EqualsAndHashCode
public class HrCompanyConfVO  {

    private static final long serialVersionUID = 149409684;

    private Integer   companyId;
    private Integer   themeId;
    private Integer   hbThrottle;
    private String    appReply;
    private Timestamp createTime;
    private Timestamp updateTime;
    private String    employeeBinding;
    private String    recommendPresentee;
    private String    recommendSuccess;
    private String    forwardMessage;
    private Short     applicationCountLimit;
    private Short     schoolApplicationCountLimit;
    private String    jobCustomTitle;
    private String    searchSeq;
    private String    searchImg;
    private String    jobOccupation;
    private String    teamnameCustom;
    private Timestamp applicationTime;
    private Integer   newjdStatus;
    private Byte      hrChat;
    private Byte      showInQx;
    private String    employeeSlug;
    private Byte      talentpoolStatus;
    private String    displayLocale;

}
