/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;


/**
 * 公司表
 */
@Data
@EqualsAndHashCode
public class HrCompanyVO {

    private static final long serialVersionUID = -557446569;

    private Integer   id;
    private Byte      type;
    private String    name;
    private String    introduction;
    private Byte      scale;
    private String    address;
    private Byte      property;
    private String    industry;
    private String    homepage;
    private String    logo;
    private String    abbreviation;
    private String    impression;
    private String    banner;
    private Integer   parentId;
    private Integer   hraccountId;
    private Byte      disable;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Byte      source;
    private String    slogan;
    private Byte      fortune;
    private String    feature;


}
