/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 账号公司关联记录
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class HrCompanyAccountVO  {

    private Integer companyId;
    private Integer accountId;

}
