/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 账号公司关联记录
 */
@Data
@EqualsAndHashCode
public class HrCompanyAccountVO  {

    private static final long serialVersionUID = -990527953;

    private Integer companyId;
    private Integer accountId;


    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public Integer getAccountId() {
        return accountId;
    }

    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
}
