/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 员工认证自定义字段表
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class HrEmployeeCustomFieldsVO {

    private Integer id;
    private Integer companyId;
    private String  fname;
    private String  fvalues;
    private Integer forder;
    private Byte    disable;
    private Integer mandatory;
    private Integer status;
    private Integer optionType;


}
