/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * HR反馈表
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class HrFeedbackVO {

    private static final long serialVersionUID = 1170798295;

    private Integer   id;
    private Integer   hraccountId;
    private String    name;
    private String    email;
    private String    images;
    private String    content;
    private Timestamp createTime;
    private Timestamp updateTime;


}
