/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * This class is generated by jOOQ.
 */
@Data
@EqualsAndHashCode
public class HrGroupCompanyVO   {

    private static final long serialVersionUID = -137763830;

    private Integer   id;
    private String    name;
    private Timestamp createTime;
    private Timestamp updateTime;


}
