/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * This class is generated by jOOQ.
 */
@Data
@EqualsAndHashCode
public class HrGroupCompanyRelVO   {

    private static final long serialVersionUID = 578142289;

    private Integer   id;
    private Integer   companyId;
    private Integer   groupId;
    private Timestamp createTime;
    private Timestamp updateTime;


}
