/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * This class is generated by jOOQ.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class HrGroupCompanyRelVO   {

    private static final long serialVersionUID = 578142289;

    private Integer   id;
    private Integer   companyId;
    private Integer   groupId;
    private Timestamp createTime;
    private Timestamp updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}
