/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 专题传播统计去重信息表
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class HrHtml5UniqueStatisticsVO   {

    private static final long serialVersionUID = 1770418267;

    private Integer id;
    private Integer topicId;
    private Integer companyId;
    private Integer viewNumUv;
    private Integer recomViewNumUv;
    private Date    createDate;
    private Integer infoType;

}
