/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 专题传播统计次数表
 */
@Data
@EqualsAndHashCode
public class HrHtml5StatisticsVO   {

    private static final long serialVersionUID = -1611455082;

    private Integer id;
    private Integer topicId;
    private Integer companyId;
    private Integer viewNumPv;
    private Integer recomViewNumPv;
    private Date    createDate;

}
