/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 企业用户导入数据异步处理监控操作表
 */
@Data
@EqualsAndHashCode
public class HrImporterMonitorVO   {

    private static final long serialVersionUID = -451730042;

    private Integer   id;
    private Integer   companyId;
    private Integer   hraccountId;
    private Byte      type;
    private String    file;
    private Short     status;
    private String    message;
    private Timestamp createTime;
    private Timestamp updateTime;
    private String    name;
    private Byte      sys;

}
