/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * hr推荐同行表
 */
@Data
@EqualsAndHashCode
public class HrNpsRecommendVO  {

    private static final long serialVersionUID = 785201733;

    private Integer   id;
    private Integer   hrNpsId;
    private String    username;
    private String    mobile;
    private String    company;
    private Timestamp createTime;

}
