/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * hr推荐同行表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "hr推荐同行信息")
public class HrNpsRecommendVO  {

    private Integer   id;
    @ApiModelProperty(value = "hr_nps调研id")
    private Integer   hrNpsId;
    @ApiModelProperty(value = "推荐的用户")
    private String    username;
    @ApiModelProperty(value = "推荐的用户的手机号")
    private String    mobile;
    @ApiModelProperty(value = "推荐的用户所属公司")
    private String    company;
    private Timestamp createTime;


}
