/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * nps打分推荐表
 */
@Data
@EqualsAndHashCode
public class HrNpsVO   {

    private static final long serialVersionUID = 1253734684;

    private Integer   id;
    private Integer   hrAccountId;
    private Byte      intention;
    private Byte      acceptContact;
    private Timestamp createTime;
    private Timestamp updateTime;

}
