/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * hr推荐同行表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "hr推荐同行信息")
public class HrNpsRecommendVO  {

    private Integer   id;
    @ApiModelProperty(value = "hr_nps调研id")
    private Integer   hrNpsId;
    @ApiModelProperty(value = "推荐的用户")
    private String    username;
    @ApiModelProperty(value = "推荐的用户的手机号")
    private String    mobile;
    @ApiModelProperty(value = "推荐的用户所属公司")
    private String    company;
    private Timestamp createTime;


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getHrNpsId() {
        return hrNpsId;
    }

    public void setHrNpsId(Integer hrNpsId) {
        this.hrNpsId = hrNpsId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }
}
