/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * hr申请状态操作记录
 */
@Data
@EqualsAndHashCode
public class HrOperationRecordVO   {

    private static final long serialVersionUID = 444810340;

    private Integer   id;
    private Long      adminId;
    private Long      companyId;
    private Long      appId;
    private Long      statusId;
    private Timestamp optTime;
    private Integer   operateTplId;

}
