/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 雇主积分规则配置表
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class HrPointsConfVO {

    private static final long serialVersionUID = 461233877;

    private Integer   id;
    private Integer   companyId;
    private String    statusName;
    private Long      reward;
    private String    description;
    private Byte      isUsing;
    private Byte      orderNum;
    private Timestamp _UpdateTime;
    private String    tag;
    private Byte      isApplierSend;
    private String    applierFirst;
    private String    applierRemark;
    private Byte      isRecomSend;
    private String    recomFirst;
    private String    recomRemark;
    private Integer   templateId;

}
