/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 资源集合表
 */
@Data
@EqualsAndHashCode
public class HrResourceVO   {

    private static final long serialVersionUID = 548971392;

    private Integer   id;
    private String    resUrl;
    private Integer   resType;
    private String    remark;
    private Integer   companyId;
    private String    title;
    private Integer   disable;
    private Timestamp updateTime;
    private Timestamp createTime;
    private String    cover;

}
