/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 候选人列表常用筛选项
 */
@Data
@EqualsAndHashCode
public class HrSearchConditionVO   {

    private static final long serialVersionUID = -1291749181;

    private Integer   id;
    private String    name;
    private String    publisher;
    private String    positionId;
    private String    keyword;
    private String    submitTime;
    private String    workYears;
    private String    cityName;
    private String    degree;
    private String    pastPosition;
    private Integer   inLastJobSearchPosition;
    private Integer   minAge;
    private Integer   maxAge;
    private String    intentionCityName;
    private Integer   sex;
    private String    intentionSalaryCode;
    private String    companyName;
    private Integer   inLastJobSearchCompany;
    private Integer   hrAccountId;
    private Timestamp createTime;
    private Integer   updateTime;
    private Integer   type;
    private Byte      candidateSource;
    private String    favoriteHrs;
    private Byte      isFreshGraduates;
    private Byte      isPublic;
    private Byte      isRecommend;
    private String    origins;
    private String    tagIds;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getPositionId() {
        return positionId;
    }

    public void setPositionId(String positionId) {
        this.positionId = positionId;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getSubmitTime() {
        return submitTime;
    }

    public void setSubmitTime(String submitTime) {
        this.submitTime = submitTime;
    }

    public String getWorkYears() {
        return workYears;
    }

    public void setWorkYears(String workYears) {
        this.workYears = workYears;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getDegree() {
        return degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getPastPosition() {
        return pastPosition;
    }

    public void setPastPosition(String pastPosition) {
        this.pastPosition = pastPosition;
    }

    public Integer getInLastJobSearchPosition() {
        return inLastJobSearchPosition;
    }

    public void setInLastJobSearchPosition(Integer inLastJobSearchPosition) {
        this.inLastJobSearchPosition = inLastJobSearchPosition;
    }

    public Integer getMinAge() {
        return minAge;
    }

    public void setMinAge(Integer minAge) {
        this.minAge = minAge;
    }

    public Integer getMaxAge() {
        return maxAge;
    }

    public void setMaxAge(Integer maxAge) {
        this.maxAge = maxAge;
    }

    public String getIntentionCityName() {
        return intentionCityName;
    }

    public void setIntentionCityName(String intentionCityName) {
        this.intentionCityName = intentionCityName;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getIntentionSalaryCode() {
        return intentionSalaryCode;
    }

    public void setIntentionSalaryCode(String intentionSalaryCode) {
        this.intentionSalaryCode = intentionSalaryCode;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public Integer getInLastJobSearchCompany() {
        return inLastJobSearchCompany;
    }

    public void setInLastJobSearchCompany(Integer inLastJobSearchCompany) {
        this.inLastJobSearchCompany = inLastJobSearchCompany;
    }

    public Integer getHrAccountId() {
        return hrAccountId;
    }

    public void setHrAccountId(Integer hrAccountId) {
        this.hrAccountId = hrAccountId;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Integer getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Byte getCandidateSource() {
        return candidateSource;
    }

    public void setCandidateSource(Byte candidateSource) {
        this.candidateSource = candidateSource;
    }

    public String getFavoriteHrs() {
        return favoriteHrs;
    }

    public void setFavoriteHrs(String favoriteHrs) {
        this.favoriteHrs = favoriteHrs;
    }

    public Byte getIsFreshGraduates() {
        return isFreshGraduates;
    }

    public void setIsFreshGraduates(Byte isFreshGraduates) {
        this.isFreshGraduates = isFreshGraduates;
    }

    public Byte getIsPublic() {
        return isPublic;
    }

    public void setIsPublic(Byte isPublic) {
        this.isPublic = isPublic;
    }

    public Byte getIsRecommend() {
        return isRecommend;
    }

    public void setIsRecommend(Byte isRecommend) {
        this.isRecommend = isRecommend;
    }

    public String getOrigins() {
        return origins;
    }

    public void setOrigins(String origins) {
        this.origins = origins;
    }

    public String getTagIds() {
        return tagIds;
    }

    public void setTagIds(String tagIds) {
        this.tagIds = tagIds;
    }
}
