/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 升级超级账号申请表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "升级超级账号申请")
public class HrSuperaccountApplyVO   {

    private static final long serialVersionUID = -75232993;

    private Integer   id;
    private Integer   companyId;
    @ApiModelProperty(value = "营业执照")
    private byte[]    licence;
    private Timestamp createTime;
    private Timestamp updateTime;
    @ApiModelProperty(value = "config_sys_administrator.id")
    private Integer   operate;
    @ApiModelProperty(value = "申请状态 0表示已经通过，1表示未处理，2表示未通过")
    private Integer   status;
    @ApiModelProperty(value = "审核留言")
    private String    message;
    private String    childCompanyId;
    @ApiModelProperty(value = "迁移时间")
    private Timestamp migrateTime;
    @ApiModelProperty(value = "子账号数量限制")
    private Integer   accountLimit;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public byte[] getLicence() {
        return licence;
    }

    public void setLicence(byte[] licence) {
        this.licence = licence;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getOperate() {
        return operate;
    }

    public void setOperate(Integer operate) {
        this.operate = operate;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getChildCompanyId() {
        return childCompanyId;
    }

    public void setChildCompanyId(String childCompanyId) {
        this.childCompanyId = childCompanyId;
    }

    public Timestamp getMigrateTime() {
        return migrateTime;
    }

    public void setMigrateTime(Timestamp migrateTime) {
        this.migrateTime = migrateTime;
    }

    public Integer getAccountLimit() {
        return accountLimit;
    }

    public void setAccountLimit(Integer accountLimit) {
        this.accountLimit = accountLimit;
    }
}
