/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 升级超级账号申请表
 */
@Data
@EqualsAndHashCode
public class HrSuperaccountApplyVO   {

    private static final long serialVersionUID = -75232993;

    private Integer   id;
    private Integer   companyId;
    private byte[]    licence;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Integer   operate;
    private Integer   status;
    private String    message;
    private String    childCompanyId;
    private Timestamp migrateTime;
    private Integer   accountLimit;


}
