/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 团队成员信息
 */
@Data
@EqualsAndHashCode
public class HrTeamMemberVO   {

    private static final long serialVersionUID = 283238950;

    private Integer   id;
    private String    name;
    private String    title;
    private String    description;
    private Integer   teamId;
    private Integer   userId;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Integer   resId;
    private Integer   disable;
    private Integer   orders;

}
