/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 团队信息
 */
@Data
@EqualsAndHashCode
public class HrTeamVO  {

    private static final long serialVersionUID = 1998937487;

    private Integer   id;
    private String    name;
    private String    summary;
    private String    description;
    private Integer   showOrder;
    private String    jdMedia;
    private Integer   companyId;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Integer   isShow;
    private String    slogan;
    private Integer   resId;
    private String    teamDetail;
    private Integer   disable;
    private String    subTitle;
    private String    link;


}
