/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 微信图文回复表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "微信图文回复")
public class HrWxNewsReplyVO {

    private Integer id;
    @ApiModelProperty(value = "wx_rule.id, 规则ID")
    private Integer rid;
    @ApiModelProperty(value = "图文回复id，本表编号")
    private Integer parentid;
    @ApiModelProperty(value = "回复名称")
    private String  title;
    @ApiModelProperty(value = "回复描述")
    private String  description;
    @ApiModelProperty(value = "")
    private String  thumb;
    private String  content;
    @ApiModelProperty(value = "回复图片链接")
    private String  url;


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getRid() {
        return rid;
    }

    public void setRid(Integer rid) {
        this.rid = rid;
    }

    public Integer getParentid() {
        return parentid;
    }

    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
}
