/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 微信文本回复表
 */
@Data
@EqualsAndHashCode
public class HrWxBasicReplyVO {

    private static final long serialVersionUID = 606270012;

    private Integer id;
    private Integer rid;
    private String  content;


}
