/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 微信图文回复表
 */
@Data
@EqualsAndHashCode
public class HrWxNewsReplyVO {

    private static final long serialVersionUID = 1455846310;

    private Integer id;
    private Integer rid;
    private Integer parentid;
    private String  title;
    private String  description;
    private String  thumb;
    private String  content;
    private String  url;

}
