/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 微信图片回复
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "微信图片回复")
public class HrWxImageReplyVO{

    private Integer   id;
    @ApiModelProperty(value = "wx_rule.id, 规则ID")
    private Integer   rid;
    @ApiModelProperty(value = "回复图片的相对路径")
    private String    image;
    private Timestamp createTime;
    private Timestamp updateTime;

}
