/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 微信公众号表
 */
@Data
@EqualsAndHashCode
public class HrWxWechatVO  {

    private static final long serialVersionUID = -1567730135;

    private Integer   id;
    private Integer   companyId;
    private Byte      type;
    private String    signature;
    private String    name;
    private String    alias;
    private String    username;
    private String    password;
    private String    token;
    private String    appid;
    private String    secret;
    private Integer   welcome;
    private Integer   default_;
    private String    qrcode;
    private Byte      passiveSeeker;
    private Byte      thirdOauth;
    private Byte      hrRegister;
    private Integer   accessTokenCreateTime;
    private Integer   accessTokenExpired;
    private String    accessToken;
    private String    jsapiTicket;
    private Byte      authorized;
    private Integer   unauthorizedTime;
    private String    authorizerRefreshToken;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Integer   showQxQrcode;
    private Integer   showCustomTheme;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getAppid() {
        return appid;
    }

    public void setAppid(String appid) {
        this.appid = appid;
    }

    public String getSecret() {
        return secret;
    }

    public void setSecret(String secret) {
        this.secret = secret;
    }

    public Integer getWelcome() {
        return welcome;
    }

    public void setWelcome(Integer welcome) {
        this.welcome = welcome;
    }

    public Integer getDefault_() {
        return default_;
    }

    public void setDefault_(Integer default_) {
        this.default_ = default_;
    }

    public String getQrcode() {
        return qrcode;
    }

    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    public Byte getPassiveSeeker() {
        return passiveSeeker;
    }

    public void setPassiveSeeker(Byte passiveSeeker) {
        this.passiveSeeker = passiveSeeker;
    }

    public Byte getThirdOauth() {
        return thirdOauth;
    }

    public void setThirdOauth(Byte thirdOauth) {
        this.thirdOauth = thirdOauth;
    }

    public Byte getHrRegister() {
        return hrRegister;
    }

    public void setHrRegister(Byte hrRegister) {
        this.hrRegister = hrRegister;
    }

    public Integer getAccessTokenCreateTime() {
        return accessTokenCreateTime;
    }

    public void setAccessTokenCreateTime(Integer accessTokenCreateTime) {
        this.accessTokenCreateTime = accessTokenCreateTime;
    }

    public Integer getAccessTokenExpired() {
        return accessTokenExpired;
    }

    public void setAccessTokenExpired(Integer accessTokenExpired) {
        this.accessTokenExpired = accessTokenExpired;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getJsapiTicket() {
        return jsapiTicket;
    }

    public void setJsapiTicket(String jsapiTicket) {
        this.jsapiTicket = jsapiTicket;
    }

    public Byte getAuthorized() {
        return authorized;
    }

    public void setAuthorized(Byte authorized) {
        this.authorized = authorized;
    }

    public Integer getUnauthorizedTime() {
        return unauthorizedTime;
    }

    public void setUnauthorizedTime(Integer unauthorizedTime) {
        this.unauthorizedTime = unauthorizedTime;
    }

    public String getAuthorizerRefreshToken() {
        return authorizerRefreshToken;
    }

    public void setAuthorizerRefreshToken(String authorizerRefreshToken) {
        this.authorizerRefreshToken = authorizerRefreshToken;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getShowQxQrcode() {
        return showQxQrcode;
    }

    public void setShowQxQrcode(Integer showQxQrcode) {
        this.showQxQrcode = showQxQrcode;
    }

    public Integer getShowCustomTheme() {
        return showCustomTheme;
    }

    public void setShowCustomTheme(Integer showCustomTheme) {
        this.showCustomTheme = showCustomTheme;
    }
}
