/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 微信回复规则表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "微信回复规则")
public class HrWxRuleVO{

    private static final long serialVersionUID = -76037994;

    private Integer id;
    private Integer wechatId;
    @ApiModelProperty(value = "")
    private Integer cid;
    @ApiModelProperty(value = "回复规则名称")
    private String  name;
    @ApiModelProperty(value = "模块名称")
    private String  module;
    @ApiModelProperty(value = "排序")
    private Integer displayorder;
    @ApiModelProperty(value = "规则状态，0禁用，1启用，2置顶")
    private Byte    status;
    @ApiModelProperty(value = "规则获取权限，0：所有，1：员工")
    private Integer accessLevel;
    @ApiModelProperty(value = "关键字")
    private String  keywords;


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getWechatId() {
        return wechatId;
    }

    public void setWechatId(Integer wechatId) {
        this.wechatId = wechatId;
    }

    public Integer getCid() {
        return cid;
    }

    public void setCid(Integer cid) {
        this.cid = cid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getModule() {
        return module;
    }

    public void setModule(String module) {
        this.module = module;
    }

    public Integer getDisplayorder() {
        return displayorder;
    }

    public void setDisplayorder(Integer displayorder) {
        this.displayorder = displayorder;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Integer getAccessLevel() {
        return accessLevel;
    }

    public void setAccessLevel(Integer accessLevel) {
        this.accessLevel = accessLevel;
    }

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }
}
