/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 微信模块表
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class HrWxModuleVO {

    private Byte   id;
    private String name;
    private String title;
    private String version;
    private String ability;
    private String description;
    private String author;
    private String url;
    private Byte   settings;
    private String subscribes;
    private String handles;
    private Byte   isrulefields;
    private Byte   home;
    private Byte   issystem;
    private String options;
    private Byte   profile;
    private String siteMenus;
    private String platformMenus;



}
