/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 微信消息通知同步状态
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "微信消息通知同步状态")
public class HrWxWechatNoticeSyncStatusVO {

    private static final long serialVersionUID = 192885980;

    private Integer   id;
    private Integer   wechatId;
    @ApiModelProperty(value = "同步状态 0:成功, 1:行业修改失败, 2:模板数量超出上限, 3:接口调用失败")
    private Integer   status;
    @ApiModelProperty(value = "同步状态提示应该删除信息的数量")
    private Integer   count;
    private Timestamp updateTime;

}
