/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 微信消息通知同步状态
 */
@Data
@EqualsAndHashCode
public class HrWxWechatNoticeSyncStatusVO {

    private static final long serialVersionUID = 192885980;

    private Integer   id;
    private Integer   wechatId;
    private Integer   status;
    private Integer   count;
    private Timestamp updateTime;

}
