/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 微信图片回复
 */
@Data
@EqualsAndHashCode
public class HrWxImageReplyVO{

    private static final long serialVersionUID = 101740927;

    private Integer   id;
    private Integer   rid;
    private String    image;
    private Timestamp createTime;
    private Timestamp updateTime;


}
