/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 职位主题活动关系表
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class JobPositionTopicVO implements Serializable {

    private static final long serialVersionUID = -1172716168;

    private Integer positionId;
    private Integer topicId;



}
