/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 职位主题活动关系表
 */
@Data
@EqualsAndHashCode
public class JobPositionTopicVO implements Serializable {

    private static final long serialVersionUID = -1172716168;

    private Integer positionId;
    private Integer topicId;


    public Integer getPositionId() {
        return this.positionId;
    }

    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    public Integer getTopicId() {
        return this.topicId;
    }

    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }


}
