/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * 微信菜单操作日志表
 */
@Data
@EqualsAndHashCode
public class LogWxMenuRecordVO {

    private static final long serialVersionUID = 1056568374;

    private Integer   id;
    private Integer   wechatId;
    private String    name;
    private String    json;
    private Timestamp _CreateTime;
    private Integer   errcode;
    private String    errmsg;

}
