/*
 * This file is generated by jOOQ.
*/
package com.moseeker.vo.company.basic;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;


/**
 * hr账号表
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(description = "Hr信息")
public class UserHrAccountVO {

    private static final long serialVersionUID = -128443835;

    private Integer   id;
    private Integer   companyId;
    private String    mobile;
    private String    email;
    @ApiModelProperty(value = "绑定的微信账号")
    private Integer   wxuserId;
    private String    password;
    private String    username;
    @ApiModelProperty(value = "0 超级账号；1：子账号; 2：普通账号")
    private Integer   accountType;
    @ApiModelProperty(value = "子账号邀请使用，账号是否激活，1：激活；0：未激活")
    private Byte      activation;
    @ApiModelProperty(value = "1表示可用，0表示不可用")
    private Integer   disable;
    @ApiModelProperty(value = "注册时间")
    private Timestamp registerTime;
    @ApiModelProperty(value = "注册IP")
    private String    registerIp;
    @ApiModelProperty(value = "最后的登录时间")
    private Timestamp lastLoginTime;
    @ApiModelProperty(value = "最后一次登录的IP")
    private String    lastLoginIp;
    private Integer   loginCount;
    @ApiModelProperty(value = "来源1:雇主 2:官网 3:微信扫描 4:我也要招人(聚合号) 5:我也要招人(企业号) 6:我也要招人(手机官网)")
    private Integer   source;
    @ApiModelProperty(value = "下载行业报告校验码")
    private String    downloadToken;
    private Timestamp createTime;
    private Timestamp updateTime;
    private String    headimgurl;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getWxuserId() {
        return wxuserId;
    }

    public void setWxuserId(Integer wxuserId) {
        this.wxuserId = wxuserId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Integer getAccountType() {
        return accountType;
    }

    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    public Byte getActivation() {
        return activation;
    }

    public void setActivation(Byte activation) {
        this.activation = activation;
    }

    public Integer getDisable() {
        return disable;
    }

    public void setDisable(Integer disable) {
        this.disable = disable;
    }

    public Timestamp getRegisterTime() {
        return registerTime;
    }

    public void setRegisterTime(Timestamp registerTime) {
        this.registerTime = registerTime;
    }

    public String getRegisterIp() {
        return registerIp;
    }

    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp;
    }

    public Timestamp getLastLoginTime() {
        return lastLoginTime;
    }

    public void setLastLoginTime(Timestamp lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public String getLastLoginIp() {
        return lastLoginIp;
    }

    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    public Integer getLoginCount() {
        return loginCount;
    }

    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    public Integer getSource() {
        return source;
    }

    public void setSource(Integer source) {
        this.source = source;
    }

    public String getDownloadToken() {
        return downloadToken;
    }

    public void setDownloadToken(String downloadToken) {
        this.downloadToken = downloadToken;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public String getHeadimgurl() {
        return headimgurl;
    }

    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }
}
